"""
Sample scattering angles from the Mie phase function.

Monte Carlo photon transport needs a random exit direction distributed according to
the phase function.  This module builds the inverse-transform table that provides
one: ``mu_with_uniform_cdf`` returns angles spaced so that equal steps along the
cumulative distribution are equally likely, and ``generate_mie_costheta`` draws from
that table.  ``docs/06_random_deviates.ipynb`` works through the whole procedure.

Importing
---------

This module is *not* imported with the package, because it imports ``miepython``
itself and doing so from ``miepython/__init__.py`` would be circular.  Ask for it by
name::

    import numpy as np
    import miepython.monte_carlo as mc

    m, x = 1.33, 2.0                              # a water droplet
    mu, cdf = mc.mu_with_uniform_cdf(m, x, 500)   # 500-entry lookup table

    rng = np.random.default_rng(12345)
    cosines = [mc.generate_mie_costheta(mu, rng=rng) for _ in range(10000)]

Build the table once and reuse it: it costs a full Mie calculation, while each draw
off it costs one random number.  The number of table entries sets how finely the
phase function is resolved, so strongly forward-scattering spheres need more of
them.

Passing ``rng`` keeps the draws reproducible without disturbing the process-wide
``numpy.random``; omitting it falls back to that global generator.
"""

import numpy as np
import miepython as mie

__all__ = (
    "cdf",
    "mu_with_uniform_cdf",
    "generate_mie_costheta",
)


def cdf(m, x, num):
    """
    Create a CDF for unpolarized scattering uniformly spaced in cos(theta).

    The CDF covers scattered (exit) angles ranging from 180 to 0 degrees.
    (The cosines are uniformly distributed over -1 to 1.) Because the angles
    are uniformly distributed in cos(theta), the scattering function is not
    sampled uniformly and therefore huge array sizes are needed to adequately
    sample highly anisotropic phase functions.

    Since this is a cumulative distribution function, the maximum value
    should be 1.

    Args:
        m: the complex index of refraction of the sphere
        x: the size parameter of the sphere
        num: length of desired CDF array

    Returns:
        mu: array of cosines of angles
        cdf: array of cumulative distribution function values
    """
    mu = np.linspace(-1, 1, num)
    intensity_per_mu = mie.i_unpolarized(m, x, mu, norm="4pi") / num
    cdf_values = np.cumsum(intensity_per_mu)
    return mu, cdf_values


def mu_with_uniform_cdf(m, x, num):
    """
    Create a CDF for unpolarized scattering for uniform CDF.

    The CDF covers scattered (exit) angles ranging from 180 to 0 degrees.
    (The cosines are uniformly distributed over -1 to 1.) These angles mu
    correspond to uniform spacing of the cumulative distribution function
    for unpolarized Mie scattering where cdf[i] = i/(num-1).

    This is a brute force implementation that solves the problem by
    calculating the CDF at many points and then scanning to find the
    specific angles that correspond to uniform interval of the CDF.

    Since this is a cumulative distribution function, the maximum value
    should be 1.

    Args:
        m: the complex index of refraction of the sphere
        x: the size parameter of the sphere
        num: length of desired CDF array

    Returns:
        mu: array of cosines of angles (irregularly spaced)
        cdf: array of cumulative distribution function values
    """
    big_num = 2000  # large to work with x up to 10
    big_mu, big_cdf = cdf(m, x, big_num)
    mu = np.empty(num)
    cdf_values = np.empty(num)

    mu[0] = -1  # cos[180 degrees] is -1
    cdf_values[0] = 0  # initial cdf is zero

    big_k = 0  # index into big_cdf
    for k in range(1, num - 1):

        target = k / (num - 1)
        while big_cdf[big_k] < target:
            big_k += 1

        delta = big_cdf[big_k] - target
        delta_cdf = big_cdf[big_k] - big_cdf[big_k - 1]
        delta_mu = big_mu[big_k] - big_mu[big_k - 1]

        mu[k] = big_mu[big_k] - delta / delta_cdf * delta_mu  # interpolate
        cdf_values[k] = target

    #       print(' mu[',k,']=% .5f'%mu[k],' cdf[',k,']=% .5f'%cdf[k],
    #       'cdf=',big_cdf[big_k], fraction)

    mu[num - 1] = 1  # cos[0 degrees] is 1
    cdf_values[num - 1] = 1  # last cdf is one

    return [mu, cdf_values]


def generate_mie_costheta(mu_cdf, rng=None):
    """
    Generate a new scattering angle using a cdf.

    A uniformly spaced cumulative distribution function (CDF) is needed.
    New random angles are generated by selecting a random interval
    mu[i] to mu[i+1] and choosing an angle uniformly distributed over
    the interval.

    Args:
       mu_cdf: a cumulative distribution function
       rng: optional source of randomness, anything with a ``random()`` method
           such as ``numpy.random.default_rng()``.  Omitting it uses the process
           wide ``numpy.random``, whose stream a caller cannot control without
           reseeding the whole program, so pass a generator when reproducibility
           matters.

    Returns:
       The cosine of the scattering angle

    Examples:
        Draw a reproducible angle without disturbing the global stream:

        >>> import numpy as np
        >>> import miepython.monte_carlo as mc
        >>> mu, cdf = mc.mu_with_uniform_cdf(1.33, 1.7, 50)
        >>> rng = np.random.default_rng(42)
        >>> first = mc.generate_mie_costheta(mu, rng=rng)
        >>> bool(-1.0 <= first <= 1.0)
        True
        >>> bool(first == mc.generate_mie_costheta(mu, rng=np.random.default_rng(42)))
        True
    """
    if rng is None:
        rng = np.random

    # rng.random() draws from [0, 1), so int(r * num) never reaches num and
    # index + 1 stays inside the table.  No clamp is needed.
    num = len(mu_cdf) - 1
    index = int(rng.random() * num)

    x = mu_cdf[index]
    x += (mu_cdf[index + 1] - mu_cdf[index]) * rng.random()

    return x
